#!/bin/bash

TERMINAL="$(command -v urxvt)"
choice=$(compgen -c | dmenu "$@")
binary=$(awk '{print $1;}' <<< $choice)
fullpath=$(command -v $binary)

if [ -x $fullpath ]; then
  #FIXME: Wayland
  if ldd $fullpath | grep libX11 > /dev/null; then
    $choice
  else
    $TERMINAL -e "$choice"
  fi
fi
